### ISSUE TITLE
authenticate error when using the example

### ISSUE THREAD

**Issue by hankchiuhc** [f-23/react-native-passkey#17]
hi @f-23, thanks for creating this great RN library. I'm trying the example on my Android device (Samsung A53). I'm able to create account and get a valid registration result but when I try to authenticate. This error occur: 
`{"error": "NotCredentials", "message": "No viable credential is available for the the user."}`

I am using the same RegRequest.json and AuthRequest.json, only modified the rp id. The allowCredentials in AuthRequest is keeping an empty array. Is there any param in registration or auth request can cause the problem? any suggestion is appreciated.

Thanks,

**Comment by f-23** [comment]
Hi @hankchiuhc! 
Just to clarify, are you using the example `RegRequest.json` and `AuthRequest.json` from the `src/__tests__/testData` directory or your own requests from a fido server?

**Comment by hankchiuhc** [comment]
hi @f-23,

Yes, I'm using the files from example. I did not perform any server request. However, I'm not able to reproduce the issue today. I will try if I can reproduce and update the steps if found. Thanks for the reply.

**Comment by f-23** [comment]
Those json files are only included for automated testing purposes.
You will need to set up a backend which can serve you requests and validate the passkey results.
