### ISSUE TITLE
its a way to change "Sign in" to and Custom text for authorizations?

### ISSUE THREAD

**Issue by KelvinPortuphy** [f-23/react-native-passkey#18]
<img width="583" alt="Screenshot 2023-09-16 at 1 56 26 PM" src="https://github.com/f-23/react-native-passkey/assets/102290475/0aa713fc-15c5-403f-bee3-fc5e11e55dd9">

its a way to change "Sign in" to and Custom text
for authorisations that are not necessarily sign-ins?

**Comment by peterferguson** [comment]
No that modal is controlled by Apple.

The only thing you control is the name of the passkey ... presumably the email that is blurred in your screenshot

**Comment by KelvinPortuphy** [comment]
oh ok noted
thanks!
