### ISSUE TITLE
feat: Add Android support

### ISSUE THREAD

**Issue by f-23** [f-23/react-native-passkey#2]
Add support for Android. Since there is no native API for passkeys available on Android a possible workaround would be to use a web view and authenticate with the server through it.

**Comment by mTRx0** [comment]
Update: Initial Library for Android Passkeys will now be release ["soon"](https://developers.google.com/identity/passkeys/faq). I will start working on it once its being released (probably early next year).

**Comment by andrew-levy** [comment]
@f-23 This would be awesome! No rush, but what is the current status of this?

**Comment by f-23** [comment]
@andrew-levy The Android team has pushed back its plans for a native passkey API on Android, so right now it is unclear when it'll be released.

From the FAQ link above:
> For Android apps, we aim to have an initial library for passkey support soon.

I'd rather wait for this native API than implement some kind of workaround which would become obsolete within a few months.

**Comment by andrew-levy** [comment]
@f-23 Makes sense, thanks for the update. Any thoughts on adding web support to make this truly cross platform? If you're interested, I might have time to help implement that.

**Comment by f-23** [comment]
@andrew-levy I think that would definitely make a good addition! I've created #7 so we can track and discuss the details on that over there.

**Comment by zolbooo** [comment]
Great news! Android team has release an alpha version of [credentials library](https://developer.android.com/training/sign-in/passkeys). Do you any help with integration?

**Comment by f-23** [comment]
@zolbooo Sounds good! Contributions are always welcome, so if you wanna work on this you're welcome to.

**Comment by f-23** [comment]
Status update:
I was able to take a closer look at the new androidx credentials library and managed to implement a somewhat working version into `react-native-passkey`.
Since the native android library is still in a very early alpha/preview phase I would prefer to wait though until a stable version is being released. 
Even with the testing I did I've encountered a handful of bugs and issues. As soon as those are resolved the full implementation should not take to long based on what I've already managed to do.

**Comment by thymikee** [comment]
Checking this article from late March: https://medium.com/androiddevelopers/bringing-seamless-authentication-to-your-apps-using-credential-manager-api-b3f0d09e0093. Are there any updates on the state of those bugs and how Android team is addressing them? 
And thanks for working on it! 🙏🏼

**Comment by f-23** [comment]
It's looking a lot better with the newer alpha versions.
Nevertheless I've found another issue preventing me from fully implementing this yet. Created an issue on the android credentials repo for this, will have to wait and see what the Android team says.
I'm gonna keep you updated!

**Comment by matinzd** [comment]
Probably they will announce it on Google I/O.

**Comment by f-23** [comment]
Android support is now available!

Bear in mind that the native androidx credentials library is still in alpha. I'm gonna use this ticket to track any issues that might occur.

**Comment by rafaelmotta** [comment]
beta version is live, would be possible updating?

**Comment by kelvinOfoli** [comment]
> Android support is now available!
> 
> Bear in mind that the native androidx credentials library is still in alpha. I'm gonna use this ticket to track any issues that might occur.

@f-23  what version of native androidx credentials is compatible with react native passkeys at the moment,
and when would you be updating using the new beta version..?

**Comment by f-23** [comment]
RN Passkeys is using androidx credentials 1.0.0-alpha08 right now.

I'm working on updating to the latest beta version.

**Comment by f-23** [comment]
react-native-passkey has been updated to use androidx credentials 1.2.0-beta03.

Please update to 2.1.0.

**Comment by kelvinOfoli** [comment]
great!
thanks
