### ISSUE TITLE
largeBlob support

### ISSUE THREAD

**Issue by ronickg** [f-23/react-native-passkey#23]
Hi there, I am planing on uses passKeys to store some data in the [largeBlob](https://developer.apple.com/documentation/authenticationservices/asauthorizationplatformpublickeycredentialregistration) which was recently added in ios 17. ([WebAuthn Large Blob Extension](https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Large-Blob-Extension/04b294ae9e9a90cf5d1eb861ac93f1133fbdb930)) Any plans of implementing this ? I am trying to do it myself, but have never used swift before.

Mfg Ronald

**Comment by BubbleTrouble14** [comment]
I got it working on the ios side, but I dont think android supports it yet sadly. Also nothing I could find online.

**Comment by MrKevinOConnell** [comment]
@BubbleTrouble14 how did you go about implementing largeblob? Looking into this myself

**Comment by BubbleTrouble14** [comment]
@MrKevinOConnell I [forked](https://github.com/BubbleTrouble14/react-native-passkey) it and added it in myself. Note My swift coding probably isnt the best. Also if u using expo u might be able to use this [one](https://github.com/peterferguson/react-native-passkeys).

**Comment by BubbleTrouble14** [comment]
Sadly android doesnt support large blobs yet though.

**Comment by MrKevinOConnell** [comment]
this is awesome thank you @BubbleTrouble14

**Comment by vitoalmeida** [comment]
Hello! Any predictions on when this feature will be ready?

**Comment by f-23** [comment]
@vitoalmeida 
I am working on a new update which should release within the next week. It'll add more configuration options for iOS like `allowCredentials`, `excludeCredentials` and `largeBlob` among other things.

**Comment by KennyFukuya** [comment]
@f-23 Do you have plans to add PRF support for android?

**Comment by f-23** [comment]
@KennyFukuya PRF support for Android versions 13 and below will be added with that same update.

**Comment by KennyFukuya** [comment]
@f-23 First of all thank you the build.

I tried to migrate to the new release but I am currently getting `TypeError: _NativePasskey.NativePasskey.create is not a function (it is undefined)` whenever I try to create a new Passkey.

Any guesses?

**Comment by f-23** [comment]
@KennyFukuya Did you run `pod install` inside the `ios` folder after updating the npm package?

**Comment by KennyFukuya** [comment]
@f-23 I managed to make it work.

I tested prf on Android and everything seems to be alright.  I couldn't validate largeBlob on iOS right now, but whenever I do I will provide feedback.

There are a couple things that I have noticed:

1. The response from `Passkey.get` and `Passkey.create` are a string instead of `PasskeyAuthenticationResult` and `PasskeyRegistrationResult` respectively.
2. Typescript for `clientExtensionResults` is missing from both `PasskeyAuthenticationResult` and `PasskeyRegistrationResult`.

Other than that it is perfect.

Thank you

**Comment by syntag** [comment]
I am unable to successfully build `3.0.0-beta` getting this build error:
```
The following build commands failed:
SwiftCompile normal arm64 Compiling\ PasskeyDelegate.swift /apps/my-project/node_modules/react-native-passkey/ios/PasskeyDelegate.swift (in target 'react-native-passkey' from project 'Pods')
SwiftCompile normal arm64 /apps/my-project/node_modules/react-native-passkey/ios/PasskeyDelegate.swift (in target 'react-native-passkey' from project 'Pods')
(2 failures)
```

**Comment by syntag** [comment]
> @f-23 I managed to make it work.

How did you manage to get the build to pass? I tried cleaning Pods folder and reinstalling pods with no luck

**Comment by syntag** [comment]
> @f-23 I managed to make it work.

@KennyFukuya how did you manage to get it to work? I tried clearing the Pod/ directory and reinstalling pods with no luck.

**Comment by f-23** [comment]
`largeBlob` support has been added, the issues should be resolved. Feel free to open the issue again if you have any more feedback.
