### ISSUE TITLE
feat: Support for Multiple Authentication Methods

### ISSUE THREAD

**Issue by onghwan** [f-23/react-native-passkey#25]
Hello,

I am currently working with the iOS system sheet controlled by the `withSecurityKey` boolean variable. As it stands, there is no option to switch between using a passkey or a security key once the `ASAuthorizationController` is initiated. This limitation restricts the flexibility needed for a more dynamic authentication process.

I propose an enhancement where `ASAuthorizationController` can be initialized with multiple requests, allowing users to switch between authentication methods directly from the system sheet. Enabling this feature would activate the "Other Sign in Options" button on the sheet, providing users the ability to change their request method on the fly.

The desired implementation could look something like this:
```swift
let securityKeyProvider = // existing security key provider
let platformKeyProvider = // existing platform key provider

let controller = ASAuthorizationController(authorizationRequests: [platformKeyProvider, securityKeyProvider])
```

In a JavaScript context, the usage could be as follows:
```typescript
register(request) // Default to exposing only passkey.
register(request, ['passkey']) // Expose only passkey.
register(request, ['securitykey']) // Expose only security key.
register(request, ['passkey', 'securitykey']) // Initially expose passkey with an option for security key under "Other Sign in Options".
register(request, ['securitykey', 'passkey']) // Initially expose security key with an option for passkey under "Other Sign in Options".
```

This feature would greatly enhance the user experience by providing more flexibility and control over the authentication process. Could you please consider supporting this functionality?

Thank you for your time and consideration.

**Comment by f-23** [comment]
Hi @onghwan 

thank you for bringing this up! Sounds like a reasonable improvement. I will keep it in mind for the next update.
