### ISSUE TITLE
New fingerprint detected, Passkey don't show up

### ISSUE THREAD

**Issue by Koploseus** [f-23/react-native-passkey#27]
Hi!

I'm using the lib on my app, it worked perfectly until i've added a fingerprint (and then deleted) in my Android phone. Since the passkey registration don't show again (and yes it's still supported and it seems to be working on Login).

There isn't any much logs either a part from "Unknown error"

Any idea how i can increase the error logs ? or to understand why when i've added a fingerprint on my phone the passkey don't show up ? Is there a security level that need to be implemented ?

Thanks

**Comment by f-23** [comment]
Hi @Koploseus,

apologies for the late response. Did you have any luck finding the cause of this issue? Android Studio might be able to provide more details.
