### ISSUE TITLE
Doesn't work with rn new architecture on android

### ISSUE THREAD

**Issue by asimaranov** [f-23/react-native-passkey#28]
When react native newArchEnabled flag is enabled (https://reactnative.dev/docs/the-new-architecture/why) library fails with error
![telegram-cloud-photo-size-2-5276107993466919493-y](https://github.com/f-23/react-native-passkey/assets/25568730/a5692ade-3563-40e0-bd04-8363b10038bb)

Error is `Error: ENOENT: no such file or directory, lstat '/Users/andrey/projects/xraise mobile/node_modules/react-native-passkey/src'`

For some reason rn looks for `node_modules/react-native-passkey/src` instead of `node_modules/react-native-passkey/android/src`
React native migration guides do not help. Seems that something is wrong with library

**Comment by TNAJanssen** [comment]
Yes same issue here
