### ISSUE TITLE
Transports and excludeCredentials 

### ISSUE THREAD

**Issue by MikeDevBeddo** [f-23/react-native-passkey#30]
[IOS] Is there any way to specify available [transports](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialdescriptor-transports) for a key and sort keys by [excludecredentials](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-excludecredentials) ?

**Comment by rahulkumar1409** [comment]
anyone working on this?

**Comment by f-23** [comment]
Will be released in the next update.
