### ISSUE TITLE
Using react-native-passkey on TestFlight

### ISSUE THREAD

**Issue by armanmamyan** [f-23/react-native-passkey#32]
Hi there @f-23. Thank u for your work and your commitment to delivering this library to the community.

I have some questions about the testing phases of "passkey" wrapped React Native app. Maybe you already answered this question and this is the duplicated ticket, for which I'm sorry. I just couldn't find the direct answer.

I set up a simple React Native App with a passkey and tried to build and deploy it to test with iOS TestFlight. 
However, after successful deployment and install on my device, the app is just crushing silent errors without giving me any possibility to track the issue. 

Since the very first thing that has been mentioned on Lib Configuration is about credentials, I wanted to ask how to configure it when I have no domain and am deploying on TestFlight.

To have more clear understanding of setup, I'm attaching also a repository, so you can have overall idea and direct me to the fix (if it exists actually) 
https://github.com/armanmamyan/passkeyapp

**Comment by Koploseus** [comment]
I face the same issue. Did you managed to correct it?

**Comment by thoth-seshat** [comment]
yah not sure why this was closed, we are getting the same issue. Did you solve this @armanmamyan ?

**Comment by f-23** [comment]
You need a domain to be able to configure Passkeys correctly. Something like ngrok will do the job for free, this is also what I'm using while developing and testing.
I am also working on an update which should improve error logging, especially on iOS. I hope this will clear up some confusion around configuration errors.
