### ISSUE TITLE
Getting "Your app is not properly configured. Refer to the docs for help." after publishing app to play store

### ISSUE THREAD

**Issue by teshank2137** [f-23/react-native-passkey#35]
I used the 2.1.1 version of react-native-passkey and integrated the passkey feature in the android app, It works amazingly on the debug build, but after publishing the app to playstore it gives the following error during passkey creation.
`{
            "error": "NotConfigured",
            "message": "Your app is not properly configured. Refer to the docs for help."
        }`

I have added all the SHAs to the assetlinks file but it still gives the same error.

following is the file hosted at /.well-known/assetlinks.json
```
[
  {
    "relation": [
      "delegate_permission/common.handle_all_urls",
      "delegate_permission/common.get_login_creds"
    ],
    "target": {
      "namespace": "android_app",
      "package_name": "com.xxxx.xxxx",
      "sha256_cert_fingerprints": [
        "84:4XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX4:6C:56:B3:A0", #from playstore
        "FA:CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5:91:03:3B:9C", #release
        "84:CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXA:47:14:1A:C6:F5" #debug
      ]
    }
  }
]
```

I'm not sure what I'm missing.

**Comment by f-23** [comment]
@teshank2137 
Please make sure you configured your backend right. Are you using the same backend server for your debug and release builds?

**Comment by teshank2137** [comment]
Yes, I'm using the same backend server, the issue was in `progaurd-rules.pro` file, and after adding the following line it worked like a charm!
```
-if class androidx.credentials.CredentialManager
-keep class androidx.credentials.playservices.** {
  *;
}
