### ISSUE TITLE
NoCredentialException is thrown even though I have registered from credentials

### ISSUE THREAD

**Issue by sontungexpt** [f-23/react-native-passkey#36]
![image](https://github.com/f-23/react-native-passkey/assets/92097639/2fa96bb9-4d87-433d-967f-f39ed55fbf77)
```json
{
  "allowCredentials": [], 
  "challenge": "0K0t3xRESM2s7ID6TZA==", 
  "extensions": {}, 
  "rpId": "aee2-14-169-47-244.ngrok-free.app", 
  "userVerification": "required"
}
```

**Comment by f-23** [comment]
What platform does this happen on? What OS version are you using?
Please provide more information on the issue.

**Comment by KraljSamo** [comment]
I am trying to implement this into base react native app. On IOS I managed to get it all working however on Android I do receive this error.

I can successfully register the credential, however when I try to authenticate, the request fails with the same error as above. 

```
  "dependencies": {
    "axios": "^1.7.2",
    "base64url": "^3.0.1",
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-passkey": "^2.1.1"
  }, 
```

For Android testing I am using POCO F3 with OS Version 1.0.1.0.TKHEUXM and Android Version 13 TKQ1.221114.001

**Comment by f-23** [comment]
@KraljSamo react-native-passkey 3.0.0-beta included an update for the native androidx.credentials library. Has your problem been resolved by now?

**Comment by sirkostya009** [comment]
Unfortunately, this isn't a problem of this library itself, but rather of the nature of Android implementation. I consistently get this error whenever my assertion requests contain `allowCredentials` array. I suggest you try omitting it from your request and see if it would work then.

**Comment by f-23** [comment]
I'm closing this as there hasn't been any feedback in a while. If the problem persists please feel free to open this issue again.
