### ISSUE TITLE
How to sign an arbitrary message with a passkey?

### ISSUE THREAD

**Issue by akshay-rr** [f-23/react-native-passkey#37]
The README mentions the steps required to register a new passkey and authenticate with an existing passkey. How can I sign arbitrary data using the private key of a stored passkey on a user's device?

**Comment by f-23** [comment]
AFAIK this is not possible the way you described it. You may want to have a look at the [PRF extension](https://github.com/w3c/webauthn/wiki/Explainer:-PRF-extension), although this will only work on Android with react-native-passkey 3.0.0-beta.

**Comment by vserpokryl** [comment]
@f-23 as I see, the current version supports the PRF extension only on Android. What about iOS from 18.0?

**Comment by f-23** [comment]
@vserpokryl Back when I implemented this iOS only supported the largeBlob extension. Looks like they've since added support for PRF. I've created an issue #82 and will look into it, thank you!
