### ISSUE TITLE
How to delete passkey ?

### ISSUE THREAD

**Issue by DevRakeshKumarGupts** [f-23/react-native-passkey#39]
How to delete passkey ?

**Comment by f-23** [comment]
This is not possible as of now. iOS and Android do not allow for passkeys to be deleted programatically. The user would have to do this themselves.

**Comment by minhchienwikipedia** [comment]
@f-23  is there anyway to open settings or navigate user to where they can delete Passkey?

**Comment by f-23** [comment]
@minhchienwikipedia That's not something this package supports, but opening the settings for instance can be easily achieved using the [Linking API](https://reactnative.dev/docs/linking).
I'm not sure if there's an easy way to open the standard password manager though.
