### ISSUE TITLE
Android: No Credentials Found in 3.0.0-beta2

### ISSUE THREAD

**Issue by syntag** [f-23/react-native-passkey#46]
I have Digital Asset Links all setup for Android ([instructions](https://github.com/f-23/react-native-passkey?tab=readme-ov-file#android)), but I am getting the following error in `3.0.0-beta2` when attempting to authenticate with existing credentials from `rpId: myapp.com`:
```
{
  "error": "NoCredentials",
  "message": "No viable credential is available for the user."
}
```

This credential already exists on my relying party domain, and it works perfectly on iOS, only Android is encountering this issue. Authentication request:
```javascript
Passkey.get({
  rpId: 'myapp.com',
  timeout: 1800000,
  userVerification: 'preferred',
  challenge: encodedChallenge,
  allowCredentials: [], // expected to allow all credentials
});
```

**Comment by f-23** [comment]
@syntag Does downgrading to v2 help? The only changes made to android in v3 were an update to the underlying androidx library and error logging.

**Comment by minhchienwikipedia** [comment]
Any solution for this issue?

**Comment by minhchienwikipedia** [comment]
I don't know why but when I'm setup on our server it work without error! I have another issue can you take a look 
https://github.com/f-23/react-native-passkey/issues/85
