### ISSUE TITLE
beta-rc: Android build broken

### ISSUE THREAD

**Issue by syntag** [f-23/react-native-passkey#49]
In the latest `beta-rc` version, the Android build is completely broken.

Seems to be complaining about package namespace that was removed from `AndroidManifest.xml`

```
* What went wrong: A problem occurred evaluating script. > error Failed to build the app: No package name found. We couldn't parse the namespace from neither your build.gradle[.kts] file at /my-app/node_modules/react-native-passkey/android/build.gradle nor your package in the AndroidManifest at /my-app/node_modules/react-native-passkey/android/src/main/AndroidManifest.xml.
```

**Comment by f-23** [comment]
@syntag Apologies, there was an unintended change in one of my commits. Please check rc2, this should be resolved!

**Comment by syntag** [comment]
Confirming it's fixed now in rc2. Thanks!
