### ISSUE TITLE
Invalid challenge thrown for example challenge

### ISSUE THREAD

**Issue by peterferguson** [f-23/react-native-passkey#9]
Hey sorry for the bad issue not sure where else to ask.

I am not sure from the docs what the format for the challenge should be?

I have tried using the sample challenge from [the server response](https://github.com/webauthn-open-source/fido2-lib/blob/cbce280976aa7afb05dcddd7a5cbb3a3a5ce537e/examples/u2f-migrated-example.js#L49) in the fido2-lib but still I get logs like:

```
Error: {"error": "InvalidChallenge", "message": "The provided challenge was invalid"}
```

I understand you guys are wrapping some native modules, is there some docs for those that I could reference? Or maybe you could link to them in the readme?

**Comment by peterferguson** [comment]
Getting further with the issue it seems that the challenge should be formatted as hex but I still run into errors after this point

```
{"error": "Unknown error", "message": "An unknown error occurred"}
```
😢

**Comment by f-23** [comment]
Hi there, sorry for the confusion. 

The challenge you pass in should be a **base64 encoded** string. Please try to encode the string from the example you've linked and see if that helps.

Looks like this should be noted in the docs to prevent further issues, I will update them asap.
